# Generated by Django 5.0.1 on 2024-01-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material_pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(max_length=10, unique=True, verbose_name='Номер материального номера')),
                ('name_property', models.CharField(max_length=255, verbose_name='Наименование имущества')),
                ('reason', models.CharField(max_length=255, verbose_name='Основание')),
                ('time_registration', models.DateTimeField(max_length=255, verbose_name='Время оформления пропуска')),
                ('type_transport', models.CharField(max_length=255, verbose_name='Вид транспорта, гос номер')),
                ('where_from', models.CharField(max_length=255, verbose_name='Откуда')),
                ('where', models.CharField(max_length=255, verbose_name='Куда')),
                ('issued_pass', models.CharField(max_length=255, verbose_name='Пропуск выдал')),
                ('today_data', models.DateTimeField(max_length=255, verbose_name='Дата')),
                ('approved', models.CharField(max_length=255, verbose_name='Вывоз разрешаю')),
            ],
        ),
    ]
